jobs:
  - name: "job1"
    image: "python:3.9-slim"
    command: ["echo", "Hello from job1"]
    backoffLimit: 2
    command: ["python", "-c", "print('Hello, Kubernetes!')"]
    completions: 1
    parallelism: 1
    activeDeadlineSeconds: 60   # Completes immediately
    restartPolicy: Never
    # No nodeSelector to avoid scheduling issues
    nodeSelector: {}
    affinity: null
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

