jobs:
  - name: "job2"
    image: "busybox:latest"
    command: ["sh", "-c", "echo 'Job running'; sleep 60; echo 'Job completed'"]
    backoffLimit: 2
    completions: 1
    parallelism: 1
    activeDeadlineSeconds: 30   # Completes immediately
    restartPolicy: Never
    # No nodeSelector to avoid scheduling issues
    nodeSelector: {}
    affinity: null
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
